In [1]:
import pandas as pd
df = pd.read_csv("Indeks Standar Pencemar Udara di Provinsi DKI Jakarta 2021.csv")
df.tail(35)

,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,location
330,11/27/2021,37,56.0,41,10,45,22,56,PM25,SEDANG,DKI4
331,11/28/2021,19,33.0,41,7,47,10,47,O3,BAIK,DKI2
332,11/29/2021,29,55.0,42,8,42,12,55,PM25,SEDANG,DKI4
333,11/30/2021,46,66.0,43,10,44,17,66,PM25,SEDANG,DKI4
334,12/1/2021,63,100.0,43,13,41,30,100,PM25,SEDANG,DKI4
335,12/2/2021,35,56.0,42,7,40,14,56,PM25,SEDANG,DKI4
336,12/3/2021,54,71.0,43,9,48,17,71,PM25,SEDANG,DKI4
337,12/4/2021,50,65.0,45,13,43,16,65,PM25,SEDANG,DKI3
338,12/5/2021,53,80.0,44,17,39,29,80,PM25,SEDANG,DKI4
339,12/6/2021,62,91.0,55,23,45,57,91,PM25,SEDANG,DKI3
340,12/7/2021,179,58.0,44,12,43,21,179,PM10,TIDAK SEHAT,DKI4
341,12/8/2021,49,76.0,45,17,51,30,76,PM25,SEDANG,DKI4
342,12/9/2021,46,63.0,46,11,51,20,63,PM25,SEDANG,DKI4
343,12/10/2021,51,73.0,47,14,41,30,73,PM25,SEDANG,DKI4
344,12/11/2021,38,60.0,45,8,51,22,60,PM25,SEDANG,DKI4
345,12/12/2021,49,63.0,43,17,42,34,63,PM25,SEDANG,DKI3
346,12/13/2021,53,68.0,44,11,34,23,68,PM25,SEDANG,DKI3
347,12/14/2021,51,76.0,46,15,37,26,76,PM25,SEDANG,DKI4
348,12/15/2021,69,124.0,44,19,50,30,124,PM25,TIDAK SEHAT,DKI4
349,12/16/2021,78,136.0,43,20,34,36,136,PM25,TIDAK SEHAT,DKI4
350,12/17/2021,58,81.0,43,18,57,35,81,PM25,SEDANG,DKI4
351,12/18/2021,51,69.0,42,18,54,32,69,PM25,SEDANG,DKI4
352,12/19/2021,65,102.0,41,24,78,45,102,PM25,TIDAK SEHAT,DKI4
353,12/20/2021,57,86.0,42,13,58,20,86,PM25,SEDANG,DKI4
354,12/21/2021,62,74.0,42,19,39,49,74,PM25,SEDANG,DKI1
355,12/22/2021,65,98.0,56,28,54,65,98,PM25,SEDANG,DKI4
356,12/23/2021,70,99.0,57,19,44,44,99,PM25,SEDANG,DKI2
357,12/24/2021,36,65.0,53,15,36,52,65,PM25,SEDANG,DKI4
358,12/25/2021,56,85.0,56,23,35,62,85,PM25,SEDANG,DKI4
359,12/26/2021,44,71.0,51,15,37,34,71,PM25,SEDANG,DKI4
360,12/27/2021,75,121.0,61,23,40,47,121,PM25,TIDAK SEHAT,DKI4
361,12/28/2021,59,89.0,53,16,34,33,89,PM25,SEDANG,DKI4
362,12/29/2021,61,98.0,54,15,37,29,98,PM25,SEDANG,DKI4
363,12/30/2021,60,102.0,53,17,38,44,102,PM25,TIDAK SEHAT,DKI4
364,12/31/2021,64,90.0,52,44,37,53,90,PM25,SEDANG,DKI4

In [2]:
df.isnull().sum()

tanggal      0
pm10         0
pm25        31
so2          0
co           0
o3           0
no2          0
max          0
critical     0
categori     0
location     0
dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   365 non-null    object
 1   pm10      365 non-null    int64
 2   pm25      334 non-null    float64
 3   so2       365 non-null    int64
 4   co        365 non-null    int64
 5   o3        365 non-null    int64
 6   no2       365 non-null    int64
 7   max       365 non-null    int64
 8   critical  365 non-null    object
 9   categori  365 non-null    object
 10  location  365 non-null    object
dtypes: float64(1), int64(6), object(4)
memory usage: 31.5+ KB

In [4]:
df['categori'].value_counts()

SEDANG         223
TIDAK SEHAT    139
BAIK             3
Name: categori, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
df['categori'] = Le.fit_transform(df['categori'])
df

,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,location
0,1/1/2021,43,NaN,58,29,35,65,65,O3,1,DKI2
1,1/2/2021,58,NaN,86,38,64,80,86,PM25,1,DKI3
2,1/3/2021,64,NaN,93,25,62,86,93,PM25,1,DKI3
3,1/4/2021,50,NaN,67,24,31,77,77,O3,1,DKI2
4,1/5/2021,59,NaN,89,24,35,77,89,PM25,1,DKI3
...,...,...,...,...,...,...,...,...,...,...,...
360,12/27/2021,75,121.0,61,23,40,47,121,PM25,2,DKI4
361,12/28/2021,59,89.0,53,16,34,33,89,PM25,1,DKI4
362,12/29/2021,61,98.0,54,15,37,29,98,PM25,1,DKI4
363,12/30/2021,60,102.0,53,17,38,44,102,PM25,2,DKI4
364,12/31/2021,64,90.0,52,44,37,53,90,PM25,1,DKI4

In [6]:
df['categori'].value_counts()

1    223
2    139
0      3
Name: categori, dtype: int64

In [7]:
df['pm25'] = df['pm25'].fillna(df['pm25'].mean())
df.tail(35)

,tanggal,pm10,pm25,so2,co,o3,no2,max,critical,categori,location
330,11/27/2021,37,56.0,41,10,45,22,56,PM25,1,DKI4
331,11/28/2021,19,33.0,41,7,47,10,47,O3,0,DKI2
332,11/29/2021,29,55.0,42,8,42,12,55,PM25,1,DKI4
333,11/30/2021,46,66.0,43,10,44,17,66,PM25,1,DKI4
334,12/1/2021,63,100.0,43,13,41,30,100,PM25,1,DKI4
335,12/2/2021,35,56.0,42,7,40,14,56,PM25,1,DKI4
336,12/3/2021,54,71.0,43,9,48,17,71,PM25,1,DKI4
337,12/4/2021,50,65.0,45,13,43,16,65,PM25,1,DKI3
338,12/5/2021,53,80.0,44,17,39,29,80,PM25,1,DKI4
339,12/6/2021,62,91.0,55,23,45,57,91,PM25,1,DKI3
340,12/7/2021,179,58.0,44,12,43,21,179,PM10,2,DKI4
341,12/8/2021,49,76.0,45,17,51,30,76,PM25,1,DKI4
342,12/9/2021,46,63.0,46,11,51,20,63,PM25,1,DKI4
343,12/10/2021,51,73.0,47,14,41,30,73,PM25,1,DKI4
344,12/11/2021,38,60.0,45,8,51,22,60,PM25,1,DKI4
345,12/12/2021,49,63.0,43,17,42,34,63,PM25,1,DKI3
346,12/13/2021,53,68.0,44,11,34,23,68,PM25,1,DKI3
347,12/14/2021,51,76.0,46,15,37,26,76,PM25,1,DKI4
348,12/15/2021,69,124.0,44,19,50,30,124,PM25,2,DKI4
349,12/16/2021,78,136.0,43,20,34,36,136,PM25,2,DKI4
350,12/17/2021,58,81.0,43,18,57,35,81,PM25,1,DKI4
351,12/18/2021,51,69.0,42,18,54,32,69,PM25,1,DKI4
352,12/19/2021,65,102.0,41,24,78,45,102,PM25,2,DKI4
353,12/20/2021,57,86.0,42,13,58,20,86,PM25,1,DKI4
354,12/21/2021,62,74.0,42,19,39,49,74,PM25,1,DKI1
355,12/22/2021,65,98.0,56,28,54,65,98,PM25,1,DKI4
356,12/23/2021,70,99.0,57,19,44,44,99,PM25,1,DKI2
357,12/24/2021,36,65.0,53,15,36,52,65,PM25,1,DKI4
358,12/25/2021,56,85.0,56,23,35,62,85,PM25,1,DKI4
359,12/26/2021,44,71.0,51,15,37,34,71,PM25,1,DKI4
360,12/27/2021,75,121.0,61,23,40,47,121,PM25,2,DKI4
361,12/28/2021,59,89.0,53,16,34,33,89,PM25,1,DKI4
362,12/29/2021,61,98.0,54,15,37,29,98,PM25,1,DKI4
363,12/30/2021,60,102.0,53,17,38,44,102,PM25,2,DKI4
364,12/31/2021,64,90.0,52,44,37,53,90,PM25,1,DKI4

In [8]:
new_df = df[['pm10', 'pm25', 'so2', 'co', 'o3', 'no2', 'categori']]

In [9]:
new_df.tail(35)

     pm10   pm25  so2  co  o3  no2  categori
330    37   56.0   41  10  45   22         1
331    19   33.0   41   7  47   10         0
332    29   55.0   42   8  42   12         1
333    46   66.0   43  10  44   17         1
334    63  100.0   43  13  41   30         1
335    35   56.0   42   7  40   14         1
336    54   71.0   43   9  48   17         1
337    50   65.0   45  13  43   16         1
338    53   80.0   44  17  39   29         1
339    62   91.0   55  23  45   57         1
340   179   58.0   44  12  43   21         2
341    49   76.0   45  17  51   30         1
342    46   63.0   46  11  51   20         1
343    51   73.0   47  14  41   30         1
344    38   60.0   45   8  51   22         1
345    49   63.0   43  17  42   34         1
346    53   68.0   44  11  34   23         1
347    51   76.0   46  15  37   26         1
348    69  124.0   44  19  50   30         2
349    78  136.0   43  20  34   36         2
350    58   81.0   43  18  57   35         1
351    51   69.0   42  18  54   32         1
352    65  102.0   41  24  78   45         2
353    57   86.0   42  13  58   20         1
354    62   74.0   42  19  39   49         1
355    65   98.0   56  28  54   65         1
356    70   99.0   57  19  44   44         1
357    36   65.0   53  15  36   52         1
358    56   85.0   56  23  35   62         1
359    44   71.0   51  15  37   34         1
360    75  121.0   61  23  40   47         2
361    59   89.0   53  16  34   33         1
362    61   98.0   54  15  37   29         1
363    60  102.0   53  17  38   44         2
364    64   90.0   52  44  37   53         1

In [10]:
from sklearn.model_selection import train_test_split

features = new_df.iloc[:,:6]
label = new_df.iloc[:,6]

x_train, x_test, y_train, y_test = train_test_split(features,label,test_size=0.30, random_state=0)

In [11]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model = model.fit(x_train, y_train)

In [12]:
print(model.predict(x_test))
print(y_test)

[2 1 1 1 2 1 1 1 2 1 2 1 1 2 1 2 2 2 1 1 2 2 1 1 1 2 1 1 2 2 2 1 1 1 1 1 1
 2 2 2 2 1 1 1 1 1 1 2 2 1 2 1 2 2 1 1 2 1 1 2 0 1 1 2 1 1 1 1 1 2 2 2 2 1
 1 2 1 1 2 1 1 1 1 1 1 1 1 2 1 1 2 1 2 1 2 1 2 1 1 1 1 2 2 2 1 2 1 1 2 1]
106    2
259    1
45     1
26     1
78     2
      ..
217    2
145    1
318    1
234    2
218    2
Name: categori, Length: 110, dtype: int32

In [13]:
from sklearn.metrics import accuracy_score
hasil_prediksi = model.predict(x_test)
accuracy_score(y_test, hasil_prediksi)

0.9

In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix(hasil_prediksi, y_test)

array([[ 0,  1,  0],
       [ 0, 59,  8],
       [ 0,  2, 40]], dtype=int64)

In [15]:
hasil_prediksi = model.predict([[43, 94.694611, 58, 29, 35, 65]])
if hasil_prediksi == 1:
    print("SEDANG")
elif hasil_prediksi == 2:
    print("TIDAK SEHAT")
elif hasil_prediksi == 0:
    print("SEHAT")
else:
    print("Error")

SEDANG

C:\Users\Farhan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [16]:
hasil_prediksi = model.predict([[19, 33.0, 41, 7, 47, 10]])
if hasil_prediksi == 1:
    print("SEDANG")
elif hasil_prediksi == 2:
    print("TIDAK SEHAT")
elif hasil_prediksi == 0:
    print("SEHAT")
else:
    print("Error")

SEHAT

C:\Users\Farhan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [17]:
hasil_prediksi = model.predict([[64, 90.0, 52, 44, 37, 53]])
if hasil_prediksi == 1:
    print("SEDANG")
elif hasil_prediksi == 2:
    print("TIDAK SEHAT")
elif hasil_prediksi == 0:
    print("SEHAT")
else:
    print("Error")

SEDANG

C:\Users\Farhan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [18]:
hasil_prediksi = model.predict([[65, 102.0, 41, 24, 78, 45]])
if hasil_prediksi == 1:
    print("SEDANG")
elif hasil_prediksi == 2:
    print("TIDAK SEHAT")
elif hasil_prediksi == 0:
    print("SEHAT")
else:
    print("Error")

TIDAK SEHAT

C:\Users\Farhan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(